signs:
  first-line-text: "ctw" # Text to type into sign to create a CTW sign
ingame:
  allowed-commands:
    - spawn
    - tell
    - m
    - msg
    - t
    - whisper
    - w
    - helpop
    - report

#######################################
#                                     #
#            GAME CONFIG              #
#                                     #
#######################################

message-decorator: "" # Used in /stats
implement-spawn-cmd: true
user-fireworks-on-win: true
keep-teams-on-win: true
instakill-on-void: false
disable-fall-damage: true
global-tablist: false # Enable to have a global tablist instead of independent.
use-sql-for-kits: false # Only for Personal Kits, Global Kit always use YAML.
lobby-guard: false
kit-menu: false

vip-armors:
  blue:
    R: 181
    G: 85
    B: 255
  red:
    R: 255
    G: 169
    B: 85

sounds:
  enabled: true
  alert: NOTE_PLING
  win-wool-sound: VILLAGER_YES
  wool-pickup-sound: FIREWORK_LAUNCH
  reversing-sound: ORB_PICKUP
  team-join-sound: LEVEL_UP
  join-command: CHEST_OPEN
  map-change: LEVEL_UP
  gui: CHEST_OPEN
  team-win-sound: WITHER_DEATH
  your-stats: ORB_PICKUP
  error: ENDERDRAGON_HIT
  tip: ITEM_PICKUP
  headshot: BLAZE_DEATH

no-crafteable-items:
#  - WOOL
#  - ANVIl

no-protected-blocks:
#  - WEB

coins:
  kill: 5
  capture: 10
