# Mauccio's CTW Configuration File | v1.4
signs:
  first-line-text: "ctw" # Text to type into sign to create a CTW sign
ingame:
  allowed-commands:
    - spawn
    - tell
    - m
    - msg
    - t
    - whisper
    - w
    - helpop
    - report

# Game Settings
message-decorator: "" # Optional.
implement-spawn-cmd: true # /spawn?
user-fireworks-on-win: true
keep-teams-on-win: true
instakill-on-void: false
disable-fall-damage: true
global-tablist: false # Enable to have a global tablist instead of independent.
use-sql-for-kits: false # Only for Personal Kits, Global Kit always use YAML.
kit-menu: false # Enable Kit Service?
prohibited-msg: true # You can edit it in messages.yml (prohibited-zone)
block-spleaf-alert: true # Alert players when they spleef same team members.

no-crafteable-items: {}
#  - WOOL
#  - ANVIl

no-protected-blocks: {}
#  - WEB

# Lobby Settings
lobby:
  guard: true
  items: true
  scoreboard: true

# Vip's Armor Settings
vip-armors:
  blue:
    R: 181
    G: 85
    B: 255
  red:
    R: 255
    G: 169
    B: 85

# Sound Settings
sounds:
  enabled: true
  type: GAME
  # GAME (Game Sounds) | NOTEBLOCK (Requires NoteBlockAPI) | MIXED (Game + Noteblock)
  # - In order to modify NOTEBLOCK Sounds, you must change or edit the nbs files from /sounds folder
  # - For MIXED mode, to disable a specific sound, just change value to NONE.
  # - For MIXED mode, to use NBS file for a specific sound, just type NOTEBLOCK next to the path.
  # Example:
  # type: MIXED
  # alert: NOTE_PLING
  # win-wool:
  #   same: NONE
  #   enemy: NOTEBLOCK -> uses win-wool-enemy.nbs
  alert: NOTE_PLING # alert.nbs
  win-wool:
    same: VILLAGER_YES # win-wool-same.nbs
    enemy: VILLAGER_NO # win-wool-enemy.nbs
    generic: # win-wool-generic.nbs | For Spectators
  wool-pickup:
    same: FIREWORK_LAUNCH  # win-wool-same.nbs
    enemy: BLAZE_HIT # win-wool-enemy.nbs
    generic: FIREWORK_LAUNCH # win-wool-generic.nbs | For Spectators
  countdown: ORB_PICKUP # countdown.nbs
  team-join:
    red: LEVEL_UP # team-join-red.nbs
    blue: LEVEL_UP # team-join-blue.nbs
  join-command: CHEST_OPEN # join-command.nbs
  map-change: LEVEL_UP # map-change.nbs
  gui: CHEST_OPEN # gui.nbs
  team-win:
    same: WITHER_DEATH # team-win-same.nbs
    enemy: BLAZE_DEATH # team-win-enemy.nbs
    generic: WITHER_DEATH # team-win-generic.nbs
  stats: ORB_PICKUP # stats.nbs
  error: ENDERDRAGON_HIT # error.nbs
  tip: ITEM_PICKUP # tip.nbs
  headshot: BAT_DEATH # headshot.nbs

# Title Settings:
# Default values: 10, 30, 10
titles:
  join:
    room:
      fade-in: 10
      stay: 30
      fade-out: 10
    red:
      fade-in: 10
      stay: 30
      fade-out: 10
    blue:
      fade-in: 10
      stay: 30
      fade-out: 10
  change-map:
    fade-in: 10
    stay: 30
    fade-out: 10
  team-win:
    red:
      fade-in: 10
      stay: 30
      fade-out: 10
    blue:
      fade-in: 10
      stay: 30
      fade-out: 10
  headshot:
    fade-in: 10
    stay: 30
    fade-out: 10
  wool-pickup:
    fade-in: 10
    stay: 30
    fade-out: 10
  wool-placed:
    fade-in: 10
    stay: 30
    fade-out: 10
  countdown:
    fade-in: 10
    stay: 30
    fade-out: 10

# Coins Settings
coins:
  kill: 5
  capture: 10
